name: Default

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - name: Set up Golang
            uses: actions/setup-go@v2
            with:
              go-version: ^1.15
        - name: Check out code
            uses: actions/checkout@v2
        -name: Test
          run: cd client && go run test -v
