name: Default

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
            go-version: ^1.15
      - name: Check out code
        uses: actions/checkout@v3
      - name: Test
        run: cd client && go test -v
